name: My workflow

on:
  pull_request:
    branches: 
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo 'Hello world'
    
