name: My workflow

on:
  pull_request:
    branches: 
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: app is creating
        run: echo 'app successfull created'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: test the app
        run: echo 'Test was successfull!'

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: app will be deployed
        run: echo 'app succesfully deployed'
